// lib/lint.js - AI-First Wiki Health Check (Librarian mode)

import chalk from 'chalk';
import ora from 'ora';
import fs from 'fs';
import path from 'path';
import { globby } from 'globby';
import { callLLM, PROMPTS } from './llm.js';
import { expandHome } from './config.js';

/**
 * AI Librarian Health Check
 */
export async function lint(config, options = {}) {
  const spinner = ora(chalk.cyan('Running AI Librarian Audit...')).start();

  try {
    const wikiDir = expandHome(config.wikiPath);
    if (!fs.existsSync(wikiDir)) {
      spinner.fail(chalk.red('Wiki directory does not exist. Run compile first.'));
      return;
    }

    // LLM config overrides from CLI
    const llmOptions = {
      apiKey: options.apiKey,
      baseUrl: options.baseUrl,
      model: options.model,
      apiType: options.apiType
    };

    const files = await globby(['**/*.md'], { cwd: wikiDir, ignore: ['INDEX.md', '.xknow-history.json'] });
    
    if (files.length === 0) {
      spinner.info(chalk.yellow('Wiki is empty. Run compile first.'));
      return;
    }

    spinner.text = chalk.cyan(`Analyzing ${files.length} documents...`);

    // 1. Build Librarian context (Concept Index and Snippets)
    const indexContent = fs.readFileSync(path.join(wikiDir, 'INDEX.md'), 'utf8');
    let context = `--- Current Index ---\n${indexContent}\n\nDocument Snippets:\n`;
    
    for (const file of files) {
      const content = fs.readFileSync(path.join(wikiDir, file), 'utf8');
      context += `- ${file}: ${content.substring(0, 150).replace(/\n/g, ' ')}...\n`;
    }

    spinner.text = chalk.cyan('Step 2: Identifying knowledge gaps and connection opportunities...');

    // 2. Call LLM for Librarian Analysis
    const analysis = await callLLM([
      { role: 'system', content: PROMPTS.LINT },
      { role: 'user', content: context }
    ], llmOptions);

    // 3. Save Report
    const reportPath = path.join(wikiDir, 'LIBRARIAN_REPORT.md');
    const reportContent = `---
title: "Librarian Health Check Report"
date: ${new Date().toISOString()}
---

# 🩺 Librarian Health Check Report

${analysis}

---
*Generated by Xknow-CLI.*
`;
    fs.writeFileSync(reportPath, reportContent);

    spinner.succeed(chalk.green('✓ AI Audit complete.'));

    console.log(chalk.bold('\n📚 Librarian Report & Recommended Next Steps:'));
    console.log(`\n${analysis}\n`);
    console.log(chalk.cyan(`✓ Full report saved to: ${reportPath}\n`));

  } catch (error) {
    spinner.fail(chalk.red(`Audit failed: ${error.message}`));
  }
}
