// lib/query.js - Intelligent Q&A with Formatting and Persistence

import chalk from 'chalk';
import ora from 'ora';
import fs from 'fs';
import path from 'path';
import { globby } from 'globby';
import { callLLM, PROMPTS } from './llm.js';
import { expandHome } from './config.js';

/**
 * Intelligent Q&A
 */
export async function query(config, question, options = {}) {
  const format = options.format || 'markdown';
  const spinner = ora(chalk.cyan(`Researching KB (Format: ${format})...`)).start();

  try {
    const wikiDir = expandHome(config.wikiPath);
    if (!fs.existsSync(wikiDir)) {
      spinner.fail(chalk.red('Wiki directory does not exist. Run compile first.'));
      return;
    }

    // 1. Smarter Context Selection
    spinner.text = chalk.cyan('Step 1: Selecting relevant context from Index...');
    const indexContent = fs.readFileSync(path.join(wikiDir, 'INDEX.md'), 'utf8');
    
    // Simple relevance filter via LLM if index is large
    // For now, load Index + all Concepts + recent References.
    const conceptFiles = await globby(['concepts/*.md'], { cwd: wikiDir });
    const refFiles = await globby(['refs/**/*.md'], { cwd: wikiDir, limit: 10 }); // Limit to recent 10 refs for speed

    let context = `--- Global Index ---\n${indexContent}\n`;
    for (const f of [...conceptFiles, ...refFiles]) {
      const content = fs.readFileSync(path.join(wikiDir, f), 'utf8');
      context += `\n--- File: ${f} ---\n${content}\n`;
    }

    spinner.text = chalk.cyan('Step 2: Generating answer...');

    // 2. Call LLM for Q&A with format request
    const answer = await callLLM([
      { role: 'system', content: PROMPTS.QUERY },
      { role: 'user', content: `Current Format: ${format}\nQuestion: ${question}\n\nKB Context:\n${context}` }
    ]);

    spinner.stop();
    console.log(chalk.bold(`\n❓ ${question}\n`));
    console.log(chalk.green(`💡 Answer (${format}):`));
    console.log(`\n${answer}\n`);

    // 3. Optional Persistence (Feedback Loop)
    if (options.save) {
      const reportName = `Report-${Date.now()}.md`;
      const reportPath = path.join(wikiDir, 'concepts', reportName);
      
      const fileContent = `---
title: "Query Result: ${question}"
date: ${new Date().toISOString()}
format: ${format}
---

# ${question}

${answer}

---
*Generated by Xknow-CLI as a dynamic synthesis.*
`;
      fs.writeFileSync(reportPath, fileContent);
      console.log(chalk.cyan(`✓ Feedback saved to ${reportPath}`));
    }

  } catch (error) {
    spinner.fail(chalk.red(`Query failed: ${error.message}`));
  }
}
